# This workflow will build a package then publish to GitHub Maven Access controlled repository

name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Infrastructure
        run: docker-compose up -d
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 20
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Publish to GitHub Maven Repository
        run: mvn -DskipTests deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ secrets.GH_PACKAGE_USER }}
          ACCESS_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}