# This workflow will build a package then publish to GitHub Maven Access controlled repository

name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Infrastructure
        run: docker-compose up -d
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 20
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build
        run: mvn -DskipTests -s $GITHUB_WORKSPACE/src/main/res/.m2/settings.xml package
        env:
          USER_NAME: ${{ secrets.GH_PACKAGE_USER }}
          ACCESS_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
      - name: Move the Artifacts
        run: mv target/generated-sources/gurukulams src/main/java && ls src/main/java/com/gurukulams/model
