# This workflow will build a package then publish to GitHub Maven Access controlled repository

name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Infrastructure
        run: docker-compose up -d
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
          server-id: github
      - name: Build
        run: ./mvnw --quiet -DskipTests -s $GITHUB_WORKSPACE/src/main/res/.m2/settings.xml package
        env:
          USER_NAME: ${{ secrets.GH_PACKAGE_USER }}
          ACCESS_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
      - name: Move the Artifacts
        run: cp -rf target/generated-sources/gurukulams/* src/main/java && rm -rf target/generated-sources && ls target && sed -i '/<!--Compiler/,/End-->/d' pom.xml
      - name: Publish to GitHub Maven Repository
        run: ./mvnw -DskipTests -Dcheckstyle.skip deploy -s $GITHUB_WORKSPACE/src/main/res/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}